name: Run Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install

      - name: Build the library
        run: pnpm build
        
      - name: Run benchmarks
        run: pnpx tsx benchmark.ts > benchmark-results.txt
          
      - name: Create benchmark report
        run: |
          echo "## Benchmark Results" > benchmark-report.md
          echo "Generated on $(date)" >> benchmark-report.md
          echo "" >> benchmark-report.md
          echo "### Raw Results" >> benchmark-report.md
          echo "\`\`\`" >> benchmark-report.md
          cat benchmark-results.txt >> benchmark-report.md
          echo "\`\`\`" >> benchmark-report.md
          
      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            benchmark-results.txt
            benchmark-report.md 