name: Run Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Run benchmarks
        run: |
          cargo build --release
          # On Linux, the library will be .so instead of .dylib
          if [ -f "target/release/libjarvis.so" ]; then
            mv target/release/libjarvis.so target/release/jarvis.node
          elif [ -f "target/release/libjarvis.dylib" ]; then
            mv target/release/libjarvis.dylib target/release/jarvis.node
          fi
          pnpx tsx benchmark.ts 